# Project information
site_name: h7b
site_description: h7b public vault
site_author: h7b
site_url: https://h7b2.netlify.app/

# Repository
repo_name: h7b/h7b-mkdocs-obsidian-public
repo_url: https://github.com/h7b/h7b-mkdocs-obsidian-public
edit_uri: ""

# Configuration
theme:
    name: material
    favicon: assets/meta/favicons.png
    icon:
        logo: material/library
        repo: fontawesome/brands/git-alt
    font:
        text: Roboto
        code: Roboto Mono
    language: en
    palette:
    # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
    # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: indigo
        accent: indigo
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.expand
        - navigation.footer
        - navigation.instant
        - navigation.tracking
        - search.suggest
        - search.highlight
        - content.code.copy
        - content.action.view
        - toc.follow

# Extensions
plugins:
  - blog
  - search

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true